tests: fix test failures on upcoming `gcc-14` (#671)
Upcoming `gcc-14` enabled a few warnings into errors, like
`-Wint-conversion`. This caused `shadow` build to fail as:

    src/extended/extended.c:13:9: error:
      initialization of ‘int’ from ‘void *’ makes integer from pointer
        without a cast [-Wint-conversion]
       13 |         NULL,
          |         ^~~~

The change fixes `int ml_flags;` to take `int` instead of pointer.